# Generated by Django 4.1 on 2022-09-03 16:17

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('token', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('porcentaje_descuento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=20)),
                ('idioma', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('precio_unitario', models.IntegerField()),
                ('cantidad_inventario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Silla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(max_length=2)),
                ('columna', models.CharField(max_length=2)),
                ('tipo', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Proyeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('formato', models.CharField(max_length=20)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.pelicula')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.sala')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_unidades', models.IntegerField()),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.combo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.sala'),
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.combo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.venta')),
            ],
        ),
        migrations.AddField(
            model_name='combo',
            name='productos',
            field=models.ManyToManyField(through='cinetic_app.ProductoCombo', to='cinetic_app.producto'),
        ),
        migrations.AddField(
            model_name='combo',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.sala'),
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('proyeccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.proyeccion')),
                ('silla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.silla')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinetic_app.venta')),
            ],
        ),
    ]
